# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-10 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('txct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='writer',
            field=models.CharField(default=5, max_length=200),
            preserve_default=False,
        ),
    ]
